services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    command: ["run", "-c", "/etc/v2ray/config.json"]
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./etc:/etc/v2ray
