[general]
live_config_reload = false

[env]
TERM = "xterm-256color"

[font]
#size = 14.0

[window]
padding = { x = 2, y = 2 }

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { mods = "Control|Shift", key = "L", action = "ToggleViMode" },
  { mode = "Vi", key = "Escape", action = "ToggleViMode" }
]
